public class Character {
    private String name;
    private Integer height;
    private String gender;
    private String hair_color;
    private String eye_color;
	private String url;
    private String homeworld;
    private Integer characterNumber;
    
    public String getName(){return this.name;}
    public Integer getHeight(){return this.height;}
    public String getGender(){return this.gender;}
    public String getHairColor(){return this.hair_color;}
    public String getEyeColor(){return this.eye_color;}
    public String getUrl(){return this.url;}
    public String getHomeWorld(){return this.homeworld;}
    public Integer getCharacterNumber(){return this.characterNumber;}
}